mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=o4120cxp!
    - MYSQL_DATABASE=mydb
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"